### ISSUE TITLE
Unicode on Windows Fails

### ISSUE THREAD

**Issue by ghost** [juancarlospaco/unicodemoticon#1]
- Unicode on Windows Fails even with Python3 Qt5.
- All is encoded to UTF-8 and Oxygen Font is installed.

**MS Window**
![unicode_python3_qt5](https://cloud.githubusercontent.com/assets/1189414/5211229/d661a47a-75bb-11e4-8e69-6b938df2d904.jpg)

**A decent Operating System**
![screenshot](https://raw.githubusercontent.com/juancarlospaco/unicodemoticon/master/temp.jpg)

:sob:

**Comment by ghost** [comment]
``` python
import sys
from PyQt5.QtWidgets import QApplication, QMainWindow, QLabel
app, win = QApplication(sys.argv), QMainWindow()
win.setCentralWidget(QLabel("😸😹😺😻😼😽😾😿🐭🐵♩♫♬♪♪♭🎶①②③④⑤⑥⑦⑧⑨⑩✪✬✫⚙"))
win.show()
sys.exit(app.exec_())
```

![prueba_window_unicode](https://cloud.githubusercontent.com/assets/1189414/5269203/6e2aab62-7a3f-11e4-9e4e-169c9f66b72b.jpg)

:sob:

**Comment by kirb** [comment]
Do be sure you have [KB2729094](https://support.microsoft.com/en-us/kb/2729094) installed, and set the label font to Segoe UI Symbol. It's included in Windows 8 and newer but requires that update for Windows 7.

**Comment by ghost** [comment]
Does UnicodEmoticon work for you on Windows :grey_question: 

It does not seem to work even on other more trivial stuff, eg:
Make and connect to a Wifi which SSID has Unicode characters, the Windows Wifi TrayIcon thingy gets garbled.

We are not setting third party Fonts on third party Apps,
because that kills the purpose that is usable on whole Desktop.

I welcome Pull Request to solve this...
even if its just README instructions procedure but it should really fully work :smiley_cat:

**Comment by ghost** [comment]
Fixed by https://github.com/juancarlospaco/unicodemoticon/commit/074e4e072f758e6b601e2aa9e7733bcafe109028
_...as much as we can._
