### ISSUE TITLE
more styles in css

### ISSUE THREAD

**Issue by jerry1970** [juancarlospaco/unicodemoticon#11]
I had to change the PY file to get rid of the (in my opinion) silly random dots, ugly rounded corners and fixed transparency of the main menu. 

It would be much more flexible if you would add more CSS classes to the main and sub menus. I would like to style the active menu item. What CSS selector do I have to use?

**Comment by flying-sheep** [comment]
my opinion as well. we should do next to nothing per default and spawn a commented CSS file in the config directory (if none exists) that people can easily use to generate their own styles.

most of our default style ATM should be commented out to be available only for people who want it.
