### ISSUE TITLE
no way to exit

### ISSUE THREAD

**Issue by flying-sheep** [juancarlospaco/unicodemoticon#13]
neither right-click menu nor window have any way to close down the application

**Comment by ghost** [comment]
**Theres 3 ways to exit:**

![unicodemoticon-exit](https://cloud.githubusercontent.com/assets/1189414/12645021/caf115cc-c5a5-11e5-87ce-771a97ba56c4.jpg)

![unicodemoticon-exit2](https://cloud.githubusercontent.com/assets/1189414/12645028/d6bb79f6-c5a5-11e5-8186-ff0aa7354dc5.jpg)

![unicodemoticon-exit3](https://cloud.githubusercontent.com/assets/1189414/12645034/dc53731e-c5a5-11e5-8889-8a95b9e7a2a0.jpg)
- CTRL+C also works to exit if started from CLI.

¯|_(ツ)/¯

**Comment by ghost** [comment]
One more way to exit added, like ~4 on total or so, I think its enough :smile_cat::+1:

**Comment by flying-sheep** [comment]
i didn’t get the “Quit” menu entry before, and the hide and × button only, hid it.

so for me there were 0 ways to actually quit the process

**Comment by ghost** [comment]
:+1:   Quit added to menu too.

**Comment by flying-sheep** [comment]
jup, thanks! could you say OK to my PR?

it’ll break with every change you do and fixing it is not a nice task
