### ISSUE TITLE
Create a working single-instance check

### ISSUE THREAD

**Issue by flying-sheep** [juancarlospaco/unicodemoticon#15]
we can just use [`tendo.singleton.SingleInstance`](https://github.com/pycontribs/tendo/blob/master/tendo/singleton.py)

**Comment by juancarlospaco** [comment]
I have fixed this on the Bolierplatembed repo, it was simply that it was just logging instead of exiting when theres multiple instances. Im testing the Fix.

**Comment by ghost** [comment]
https://github.com/juancarlospaco/anglerfish#set_single_instance
