### ISSUE TITLE
Arch and Fonts Bug

### ISSUE THREAD

**Issue by ghost** [juancarlospaco/unicodemoticon#16]
On Arch Linux the fonts have missing glyphs compared to Ubuntu, even with `ttf-ancient-font` and `ttf-google-fonts` and `ttf-ubuntu-font` and `ttf-oxygen-font`.

![archbug](https://cloud.githubusercontent.com/assets/1189414/12886409/ae80b024-ce4b-11e5-955b-3aa3c9b52ec5.jpeg)

https://aur.archlinux.org/packages/unicodemoticon/

Arch comes with Python 3 and everything UTF-8.

Does Ubuntu have a more up to date font :grey_question: does Ubuntu have a patched one :grey_question: 

Posible solution is copy over from an Ubuntu installation (eg. a VirtualBox) to Arch the Font files,
try if Unicodemoticon works better, if it does release a PKGBUILD to AUR :grey_question: 

Find the Ubuntu repo URL that has the font to download it from there.

**Comment by flying-sheep** [comment]
hmm, [here](https://wiki.archlinux.org/index.php/Fonts#International_users) is a listing of some fonts for international users.

that being said, `ttf-ancient-fonts` should contain symbola, which should contain all those symbols…

maybe `noto-fonts-emoji` is better?

**Comment by ghost** [comment]
Fixed :grey_exclamation:, Thanks everyone :grey_exclamation:, Unicodemoticons depends on `noto-fonts-emoji`

@flying-sheep feel free to update the AUR when you can, add dependency on `noto-fonts-emoji`

:smile_cat:

**Comment by flying-sheep** [comment]
OK

/edit: done
