### ISSUE TITLE
Recent emoticons tab

### ISSUE THREAD

**Issue by ghost** [juancarlospaco/unicodemoticon#17]
- Research and implement a **Recent** emoticons tab.
- Recent should store chronologically, but not repeated, emoticons that were previously used.
- Have a limit to save memory, think about how much, 50 last emoji ?

:smile_cat:

**Comment by flying-sheep** [comment]
lol, “all of them” would have an adequate memory consumption as well.

**Comment by ghost** [comment]
Ye, mainly for UX.
