### ISSUE TITLE
don’t install desktop files per default

### ISSUE THREAD

**Issue by flying-sheep** [juancarlospaco/unicodemoticon#5]
KDE automatically restarts applications that run during logout, so having that autostart file will result in one more instance per system start.

also when packaging it for distros, the .desktop files should end up in `/usr/share/applications`, not `~/.local/share/applications`.

not changing this directly because i want to discuss it with you. should we do a `--install` flag that does this instead?

**Comment by ghost** [comment]
I think the real problem here, is that we need to NOT allow multiple instances,
we need to create a `*.lock` file in `/tmp`, and remove it on exit, in a crossplatform clean and simple way,
even if the app hangs, after a reboot, it should work ok again, and K.I.S.S. way.

The idea of the app is being useful and ready to use by default, 
you install it its ready for action, you dont want it you uninstall it,
kids and non-techy people will not know how to create a `*.desktop` on their computers manually.

No point of multiple instances whatsoever...

:wolf:

**Comment by juancarlospaco** [comment]
~Pseudo-Code:
```python
from tempfile import gettempdir

lock_file_path = os.path.join(gettempdir(), "unicodemoticon.lock")
try:
    if not os.path.isfile(lock_file_path):
        open(lock_file_path, "w").close()  # mimic unix touch
        main()  # run the App
    else:
        log.critical("Unicodemoticon is already running, exiting.")
except Exception as reason:
    log.critical(reason)  # really weird error if end up here
finally:
    os.remove(lock_file_path)  # clean up on exit

```

:penguin: :thought_balloon:

**Comment by ghost** [comment]
Closing solved by this UDP Unix/Local Socket solution for Single Instance https://github.com/juancarlospaco/unicodemoticon/commit/e2db1a7f160da2025a50e6af8dfe1077dcc46322

``` python
import socket, sys
try:  # Single instance app ~crossplatform, uses udp socket.
    __lock = socket.socket(socket.AF_UNIX if sys.platform.startswith("linux")
                           else socket.AF_INET, socket.SOCK_STREAM)
    __lock.bind("\0_unicodemoticon_lock"
                if sys.platform.startswith("linux") else ("127.0.0.1", 8000))
except socket.error as e:
    sys.exit("App already running, ({e},Reboot to Fix). Exiting.".format(e=e))
```

:laughing:

**Comment by flying-sheep** [comment]
1. the current way to do single-instance doesn’t work for me
2. i rather wouldn’t have the desktop file no matter if single instance mode works or not

**Comment by ghost** [comment]
Chrome/Chromium has an **Add to Desktop**, can be cool to add that to the menu:

![unicodemoticon-add-desktop](https://cloud.githubusercontent.com/assets/1189414/12645322/10be5eaa-c5a8-11e5-9186-0416fc3a3577.jpg)

:octocat:

**Comment by ghost** [comment]
Added Chrome like behaviour, optional, good enough for now... :cat:
