### ISSUE TITLE
ArchLinux Package is Outdated several versions old

### ISSUE THREAD

**Issue by ghost** [juancarlospaco/unicodemoticon#6]
- ArchLinux Package is Outdated several versions old, its `1.0.0` we are at ~`1.0.6`, needs Update.
  https://aur.archlinux.org/packages/unicodemoticon
  https://raw.githubusercontent.com/juancarlospaco/unicodemoticon/master/PKGBUILD
# ┐(;´༎ຶД༎ຶ`)┌

**Comment by flying-sheep** [comment]
ah, there are new releases!

for them to be visible on the release page we’ll have to tag them. i’ll tag the ones we have right now, but you should tag future ones as soon as you commit them:

``` shell
$ git commit -m 'new version 1.0.6'
$ git tag v1.0.6
$ git push --tags
```

if you know what’s in the new release you can also do annotated tags:

``` shell
$ git tag -a v1.0.4 -m 'new features:
* Will only start one instance
* foobar'
```

**Comment by flying-sheep** [comment]
fixed in 1b2f02b11c2a074d5137bcb13553d5a25719076e

by the way: it’s not `python-unicodemoticon` since `python-*` is for _packages_. this is an application, so just `unicodemoticon`. packages that are also applications are also without `python-` prefix (e.g. ipython)

**Comment by ghost** [comment]
Epic @flying-sheep :grey_exclamation: :+1: 

I know is not perfect, its just `#Automatically generated by pip2arch` as it says (will take note on the manual tweaks and recommendations)
from https://github.com/bluepeppers/pip2arch#pip2arch
:smile_cat:

**Comment by flying-sheep** [comment]
thanks 😀

future updates should be easy to do manually. just edit `pkgver` and `md5sums`

**Comment by ghost** [comment]
We are at V. 1.2.2
- https://pypi.python.org/pypi/unicodemoticon/1.2.2 
- https://github.com/juancarlospaco/unicodemoticon/releases/tag/v1.2.2
- https://aur.archlinux.org/packages/unicodemoticon

The PKGBUILD is up to date:
- https://github.com/juancarlospaco/unicodemoticon/blob/master/PKGBUILD

If you want, you can do your Magic @flying-sheep :smile_cat:

**Comment by flying-sheep** [comment]
done :smiley:

**Comment by ghost** [comment]
:+1:

**Comment by ghost** [comment]
@flying-sheep V 2.0 https://github.com/juancarlospaco/unicodemoticon/releases/tag/2.0.0 
https://aur.archlinux.org/packages/unicodemoticon

**Comment by flying-sheep** [comment]
done

**Comment by ghost** [comment]
https://aur.archlinux.org/packages/unicodemoticon 🙁

**Comment by flying-sheep** [comment]
whoops, sorry! at it

/edit: done

**Comment by flying-sheep** [comment]
somehow the package still shows 2.1.1 even though the git interface shows it correctly updated…

**Comment by ghost** [comment]
Thank you.
