### ISSUE TITLE
Have a "search" field

### ISSUE THREAD

**Issue by facundobatista** [juancarlospaco/unicodemoticon#7]
So, you can put a part of a char name and it will show all chars with that part in the name.

For example, you search for `"phone"` and will show (among others): `☎`

**Comment by ghost** [comment]
This is Fixed now on Master...  :smile_cat: 

New **Search Unicode** option:

![search_unicode0](https://cloud.githubusercontent.com/assets/1189414/9604047/4d7b5164-508b-11e5-827c-ba471412f5a3.jpg)

Then show up the Result and Copy it to Clipboard too:

![search_unicode1](https://cloud.githubusercontent.com/assets/1189414/9604067/736dfbf6-508b-11e5-8416-98ea2c38a673.jpg)

Copies to Clipboard:
`"☎✆📞📱📲"`

:octocat:
