### ISSUE TITLE
Have a "explain" field

### ISSUE THREAD

**Issue by facundobatista** [juancarlospaco/unicodemoticon#8]
So, you can put a char there, and will tell (at least) the name.

For example, you put `☎` and tells you `"BLACK TELEPHONE"`

**Comment by ghost** [comment]
Some Context/Implementation idea:

``` python
>>> import unicodedata
>>> unicodedata.name("☎")
'BLACK TELEPHONE'
>>> unicodedata.name("Ñ")
'LATIN CAPITAL LETTER N WITH TILDE'
```

:bulb:
